name: attendance_dashboard
description: A dashboard for attendance app admin
version: 0.0.1
homepage: https://attendance-c43bb.firebaseapp.com/
author: ammaratef45 <ammar.atef45@gmail.com>

environment:
  sdk: '>=2.0.0'

dependencies:
  angular: ^5.0.0
  firebase: ^5.0.2
  angular_components: ^0.12.0
  firebase_dart_ui: ^0.1.1

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  angular_test: ^2.0.0

